### PR TITLE
Add themr to allow themes

### PR DESCRIPTION
**Pull request by pierrickrouxel**
All components use react-css-themr.

It's now possible to build themes for react-transmission.
This allows to develop a new UI without lost the goal of keep the same UI of actual transmission web client.

### CODE REVIEW

**Comment by fcsonline** [comment]
Thanks for your contribution but it goes against one of our main project rule.

This rule says that we need to keep the same UI like the old interface before being accepted by the main Transmission project. After being accepted we can talk about changing themes and UI refactors.

**Comment by pierrickrouxel** [comment]
I didn’t change theme. All CSS stay as this. I just prepare the future. 
I think you shouldn’t reject this PR. I spent lot of time to integrate themr. I will not redo this work on the futur version.

**Comment by fcsonline** [comment]
Sorry if my answer was a bit rude. Hard days in my city, Barcelona. 😢

**Comment by jasonm23** [comment]
👍 for merging too,  this wouldn't compromise UI goals and would allow users to customize look and feel to their liking.

**Pull request closed without merging**
