### PR TITLE
Support auth

### PR DESCRIPTION
**Pull request by Secretmapper**
Support HTTP authentication

### CODE REVIEW

**Comment by edulan** [comment]
Hi @Secretmapper does this fix using transmission with basic auth enabled? I remember we tried that with no success, that's why we changed ajax implementation to a XMLHttpRequest based one. See https://github.com/fcsonline/react-transmission/pull/47

Maybe I'm missing something... :confused:

**Comment by edulan** [comment]
@Secretmapper tried again and works like a charm! Thanks for your help

**Comment by Secretmapper** [comment]
:+1: This was so tricky to debug - I was pulling my hair out on why it wouldn't work while we're doing seemingly the same thing as transmission's web ui, and it just turns out jquery has it enabled as a default option (and hence why it didn't show up on transmission's codebase).

**Comment by fcsonline** [comment]
It isn't jquery. The browser does this things for you with ajax or whatever http request. The problem was the new `fetch` way that you need to specify all the headers you want to send.

**Pull request merged**
